"""
Monte Carlo / robustness testing (spec section 16).

Resamples a strategy's OWN historical (out-of-sample, ideally) trade
results to estimate the RANGE of outcomes -- drawdown, losing-streak
length, total return, and the probability of an adverse sequence -- that a
similar run of trades could plausibly have produced.

Two resampling methods, answering two different questions:
  * "bootstrap" (sample WITH replacement, `trades_per_simulation` draws per
    simulation): "if the underlying distribution of trade outcomes is like
    the one observed, how much could total return/drawdown/streak length
    vary from a different SAMPLE of similar trades?"
  * "shuffle" (a permutation of the EXACT SAME trades, no replacement,
    `trades_per_simulation` forced to equal the number of historical
    trades): "holding the exact set of trades fixed, how much could
    drawdown/losing-streak have varied just from a different ORDER they
    happened to arrive in?" This is the direct answer to the spec's
    "probability of adverse sequences" -- the trades are identical to what
    actually happened; only the sequencing is randomized.

THIS IS NOT A FORECAST. It answers "how much variation is plausible from
sampling/sequencing luck alone, given trades like these" -- never "what
will this strategy earn next year." `MonteCarloReport.disclaimer` repeats
this, and every summary/report string generated by this module says so
too; do not strip that context out when displaying these numbers.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Sequence

import numpy as np

from backtesting.metrics import longest_losing_streak, max_drawdown

DISCLAIMER = (
    "This is a resampling/resequencing exercise over trades that ALREADY happened -- it estimates "
    "how much variation in drawdown/streak/return would be plausible from sampling or ordering luck "
    "alone, given trades like these. It is NOT a prediction of future profit, and a favorable "
    "distribution here does not mean the strategy will perform this way going forward: the whole "
    "exercise is only as good as the trade sample it was built from (out-of-sample walk-forward "
    "trades are a far more honest input to this than in-sample/training trades)."
)


@dataclass
class MonteCarloReport:
    method: str                       # "bootstrap" or "shuffle"
    num_simulations: int
    trades_per_simulation: int
    initial_capital: float
    actual_total_return_pct: float
    actual_max_drawdown_pct: float
    actual_longest_losing_streak: int
    total_return_pct_distribution: List[float] = field(default_factory=list)   # sorted ascending
    max_drawdown_pct_distribution: List[float] = field(default_factory=list)   # sorted ascending (more negative = worse, first)
    losing_streak_distribution: List[int] = field(default_factory=list)        # sorted ascending
    final_equity_distribution: List[float] = field(default_factory=list)       # sorted ascending
    probability_of_ruin: float = 0.0             # fraction of sims whose equity path touched <= 0
    probability_of_net_loss: float = 0.0         # fraction of sims ending with total_return_pct <= 0
    probability_of_worse_drawdown_than_actual: float = 0.0
    percentiles: Dict[int, Dict[str, float]] = field(default_factory=dict)
    insufficient_data: bool = False
    disclaimer: str = DISCLAIMER

    def probability_drawdown_worse_than(self, threshold_pct: float) -> float:
        """Fraction of simulations whose max drawdown exceeded (was more
        negative than) `threshold_pct` (given as a positive fraction, e.g.
        0.20 for a 20% drawdown). Returns nan if no simulations were run."""
        if not self.max_drawdown_pct_distribution:
            return float("nan")
        threshold = -abs(threshold_pct)
        worse = sum(1 for d in self.max_drawdown_pct_distribution if d <= threshold)
        return worse / len(self.max_drawdown_pct_distribution)

    def summary(self) -> str:
        lines = [
            f"Monte Carlo robustness ({self.method}, {self.num_simulations} simulations of "
            f"{self.trades_per_simulation} trades each):",
        ]
        if self.insufficient_data:
            lines.append(
                "  INSUFFICIENT DATA: too few historical trades to resample meaningfully -- the "
                "numbers below are shown for completeness only and should not be trusted."
            )
        lines.append(f"  Actual (as it happened): return={self.actual_total_return_pct:.2%}, "
                      f"max_drawdown={self.actual_max_drawdown_pct:.2%}, "
                      f"longest_losing_streak={self.actual_longest_losing_streak}")
        for p in sorted(self.percentiles.keys()):
            row = self.percentiles[p]
            lines.append(
                f"  P{p}: return={row['total_return_pct']:.2%}, max_drawdown={row['max_drawdown_pct']:.2%}, "
                f"losing_streak={row['losing_streak']:.0f}"
            )
        lines.append(f"  Probability of ruin (equity <= 0 at some point): {self.probability_of_ruin:.1%}")
        lines.append(f"  Probability of a net loss overall: {self.probability_of_net_loss:.1%}")
        lines.append(
            f"  Probability of a WORSE drawdown than actually happened: "
            f"{self.probability_of_worse_drawdown_than_actual:.1%}"
        )
        lines.append(f"  {self.disclaimer}")
        return "\n".join(lines)


def _simulate_equity(pnls: Sequence[float], initial_capital: float) -> List[float]:
    equity = [initial_capital]
    for p in pnls:
        equity.append(equity[-1] + p)
    return equity


def run_monte_carlo(
    trade_pnls: Sequence[float],
    initial_capital: float,
    num_simulations: int = 2000,
    trades_per_simulation: Optional[int] = None,
    method: str = "bootstrap",
    seed: Optional[int] = None,
    min_trades_recommended: int = 20,
    percentiles: Sequence[int] = (5, 10, 25, 50, 75, 90, 95),
) -> MonteCarloReport:
    """
    `trade_pnls` should be REAL, already-realized net P&L per trade (spec
    section 16: "using historical trade results") -- ideally out-of-sample
    trades from a walk-forward run, never fabricated or invented values.

    `method='bootstrap'` samples `trades_per_simulation` trades WITH
    replacement per simulation (default: same count as the input).
    `method='shuffle'` permutes the exact input trades (forces
    `trades_per_simulation` to equal `len(trade_pnls)`, since a shuffle
    without replacement can't produce a different count) -- see the module
    docstring for what each answers.
    """
    if method not in ("bootstrap", "shuffle"):
        raise ValueError(f"method must be 'bootstrap' or 'shuffle', got {method!r}")

    pnls = list(trade_pnls)
    n = len(pnls)
    rng = np.random.default_rng(seed)

    actual_equity = _simulate_equity(pnls, initial_capital)
    actual_total_return_pct = (actual_equity[-1] - initial_capital) / initial_capital if initial_capital else 0.0
    actual_mdd = max_drawdown(actual_equity)
    actual_streak = longest_losing_streak(pnls)

    if n == 0:
        return MonteCarloReport(
            method=method, num_simulations=0, trades_per_simulation=0, initial_capital=initial_capital,
            actual_total_return_pct=0.0, actual_max_drawdown_pct=0.0, actual_longest_losing_streak=0,
            insufficient_data=True,
            disclaimer=DISCLAIMER + " No trades were supplied at all -- nothing was simulated.",
        )

    if method == "shuffle":
        trades_per_simulation = n
    else:
        trades_per_simulation = trades_per_simulation or n

    insufficient = n < min_trades_recommended

    final_equities: List[float] = []
    total_returns: List[float] = []
    mdds: List[float] = []
    streaks: List[int] = []
    ruin_count = 0

    for _ in range(num_simulations):
        if method == "bootstrap":
            sim_pnls = rng.choice(pnls, size=trades_per_simulation, replace=True).tolist()
        else:  # shuffle
            sim_pnls = rng.permutation(pnls).tolist()

        equity = _simulate_equity(sim_pnls, initial_capital)
        final_equities.append(equity[-1])
        total_returns.append((equity[-1] - initial_capital) / initial_capital if initial_capital else 0.0)
        mdds.append(max_drawdown(equity))
        streaks.append(longest_losing_streak(sim_pnls))
        if min(equity) <= 0:
            ruin_count += 1

    final_equities.sort()
    total_returns.sort()
    mdds.sort()
    streaks.sort()

    probability_of_ruin = ruin_count / num_simulations if num_simulations else 0.0
    probability_of_net_loss = (sum(1 for r in total_returns if r <= 0) / num_simulations) if num_simulations else 0.0
    probability_worse_drawdown = (
        sum(1 for d in mdds if d <= actual_mdd) / num_simulations
    ) if num_simulations else 0.0

    def _pctl(sorted_vals, pct):
        if not sorted_vals:
            return float("nan")
        idx = int(round((pct / 100) * (len(sorted_vals) - 1)))
        idx = max(0, min(len(sorted_vals) - 1, idx))
        return sorted_vals[idx]

    pct_table: Dict[int, Dict[str, float]] = {}
    for p in percentiles:
        pct_table[p] = {
            "total_return_pct": _pctl(total_returns, p),
            "max_drawdown_pct": _pctl(mdds, p),
            "losing_streak": float(_pctl(streaks, p)),
            "final_equity": _pctl(final_equities, p),
        }

    disclaimer = DISCLAIMER
    if insufficient:
        disclaimer += (
            f" Only {n} historical trade(s) were available (fewer than the recommended "
            f"{min_trades_recommended}) -- these distributions are especially unreliable with this "
            "little underlying data."
        )

    return MonteCarloReport(
        method=method, num_simulations=num_simulations, trades_per_simulation=trades_per_simulation,
        initial_capital=initial_capital,
        actual_total_return_pct=actual_total_return_pct, actual_max_drawdown_pct=actual_mdd,
        actual_longest_losing_streak=actual_streak,
        total_return_pct_distribution=total_returns, max_drawdown_pct_distribution=mdds,
        losing_streak_distribution=streaks, final_equity_distribution=final_equities,
        probability_of_ruin=probability_of_ruin, probability_of_net_loss=probability_of_net_loss,
        probability_of_worse_drawdown_than_actual=probability_worse_drawdown,
        percentiles=pct_table, insufficient_data=insufficient, disclaimer=disclaimer,
    )
